### ISSUE TITLE
Beeline.startTrace(...) creating noop spans with empty context

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-java#25]
Given code like this:

```java
spanBuilderFactory = Tracing.createSpanBuilderFactory(postProcessor, Sampling.alwaysSampler());
tracer = Tracing.createTracer(spanBuilderFactory);
beeline = Tracing.createBeeline(tracer, spanBuilderFactory);

beeline.startTrace("root", PropagationContext.emptyContext(), "service");
```

One would expect it to start traces correctly but instead the empty context results in `NoopSpan`s. The `Beeline` expects an existing context e.g., from HTTP header. However, calling the underlying `Tracer` directly to generate the trace works after creating a span using the underlying `SpanBuilderFactory`:

```java
spanBuilderFactory = Tracing.createSpanBuilderFactory(postProcessor, Sampling.alwaysSampler());
tracer = Tracing.createTracer(spanBuilderFactory);
beeline = Tracing.createBeeline(tracer, spanBuilderFactory);

Span rootSpan = beeline.getSpanBuilderFactory().createBuilder()
    .setSpanName("root")
    .setServiceName("service")
    .build();

TracerSpan rootTracerSpan = beeline.getTracer().startTrace(rootSpan);
```

The latter seems to be the expected API today - but it feels like the former should work too. After all, an empty context should probably just start a trace. Maybe we can fix this up.

**Comment by KaoruDev** [comment]
I started reading the code and was wondering how a `server` would not whether or not the trace in the request should not be sampled or not. For example, consider this scenario:

Given:
- A request hops from `mobile client` -> `API server` -> `Backend Server` -> `DB`

When:
- The `API server` receives a request and assigns creates a trace id of `trace_id_one`. Due to its sampling configurations, it decides it _won't_ sample `trace_id_one`.

Then:
- How will the `Backend Server` know that `trace_id_one` should not be sampled?

Turns out that when a trace is started with an empty context, it's considered a NoOp.

Here's the code:

Client injects header into request:
https://github.com/honeycombio/beeline-java/blob/6b2fc3d93f797a953b0b7afc4beb765395c1ae47/beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagator.java#L70-L75

If a trace has an empty context, i.e. it's a Noop, `HttpClientPropagator` will not inject a header:
https://github.com/honeycombio/beeline-java/blob/6b2fc3d93f797a953b0b7afc4beb765395c1ae47/beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagator.java#L110-L115

On the server side, the trace is restarted:
https://github.com/honeycombio/beeline-java/blob/6b2fc3d93f797a953b0b7afc4beb765395c1ae47/beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagator.java#L80-L91

And an empty context is returned if the header is missing:
https://github.com/honeycombio/beeline-java/blob/6b2fc3d93f797a953b0b7afc4beb765395c1ae47/beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodec.java#L90-L92

**Comment by vreynolds** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
