### ISSUE TITLE
[Opinion] Setting sampleRate then calling sendPresample is confusing

### ISSUE THREAD

**Issue by KaoruDev** [honeycombio/beeline-java#29]
In `SendingSpan` we set the sample rate on the event but then call `Event#sendPresampled()`

https://github.com/honeycombio/beeline-java/blob/master/beeline-core/src/main/java/io/honeycomb/beeline/tracing/SendingSpan.java#L67

Seems confusing since `sendPresampled` ignores sampling rate, AFAIK

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
