### ISSUE TITLE
No way to get ahold of Beeline for additional spans/tags in BeelineServletFilter?

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-java#31]
I can't figure out any way to get access to a `Beeline` when using https://github.com/honeycombio/beeline-java/blob/v1.1.0/beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/BeelineServletFilter.java to create additional child spans and/or add custom fields

@paulosman @asdvalenzuela any ideas?

**Comment by nathanleclaire** [comment]
Often in other beelines this is stashed on the request context. In Spring I know we use the DI system to inject it, but I'm not sure that's possible when using the generic servlet filter in Spring 1 or other systems. That's what I do [here](https://gist.github.com/nathanleclaire/05960f41504acc3f8b0c0682caaf9ad9#file-honeycombfilter-java-L43) for instance.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
