### ISSUE TITLE
DebugResponseObserver should be in core (or libhoney) not spring-boot-starter

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-java#33]
There are many cases where we might want a `DebugRepsonseObserver` that aren't Spring specific. It should be in the Beeline core or in libhoney-java itself

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
