### ISSUE TITLE
No AddFieldToTrace

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-java#34]
I couldn't find any equivalent at least. Would be nice to have a way to add a field to all spans in a trace, sometimes you just want to thread that stuff through everywhere.

**Comment by paulosman** [comment]
Interestingly there's a `addTraceField` method in the `Span` class that stores the parameters in a separate field. It doesn't appear to propagate those fields to other spans in the trace however, so that may be where the bug is.

**Comment by vgw-LeeCampbell** [comment]
I thought that this would make sense for marking a trace with an `isError` field. 
Then my custom sampler could check that as as part of its sample alg.

However it appears that the TraceFields are passed as copies, so updating them on one span has no(?) affect on other spans in the trace.

With this in mind, I am not sure how Java users are doing the "sample 200s, but send all 400/500s" approach I have heard recommended.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
