### ISSUE TITLE
No way to continue instrumenting in concurrent stuff - traceRunnable, traceFunction

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-java#35]
I can't figure out any way (and I don't know that there is one) to continue doing `beeline.getTracer().startSpan`, `addField`, etc., within the concurrency abstractions that we have in `Tracer` (`traceRunnable`, `traceFunction`, etc). That's kinda a bummer cause sometimes I want to break off an async part of the trace but not have to go through all the hoopla to get a brand new `Beeline` or `Tracer` instance.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
