### ISSUE TITLE
Disable Beeline if no write-key is provided (Spring Boot)

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/beeline-java#40]
Hi, I'm using the Spring Boot starter beeline. So far setting this up has been a breeze.

Since I don't want to check in the API key, I plan to inject the write-key using the environment variable `HONEYCOMB_BEELINE_WRITEKEY`.

Unfortunately, when we boot the application in CI we get this error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'honeycomb.beeline' to io.honeycomb.beeline.spring.autoconfig.BeelineProperties failed:

    Property: honeycomb.beeline.writeKey
    Value: null
    Reason: The Beeline requires a write key to be configured


Action:

Update your application's configuration
```

This is caused by `BeelineProperties`, which has a not empty constraint on write-key: https://github.com/honeycombio/beeline-java/blob/master/beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineProperties.java#L25

Would it be possible to relax this and simply disable the whole beeline if no write-key is provided? I think this is more similar to how the Go beeline works.
The application doesn't crash if we simply enter a dummy value so that's currently our workaround 😅

As a side note, our CI is also instrumented with buildevents. Would it be possible to attach traces generated by the tests to the trace from buildevents?

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
