### ISSUE TITLE
Sleuth is not propagating span / trace IDs as expected

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/beeline-java#69]
Raised via tweeter: https://twitter.com/osi/status/1293688725789007872

Gist to show working span handler: https://gist.github.com/osi/a496506f36929c90d24712bbd0368a40

**Comment by osi** [comment]
You're welcome to incorporate my changes back into the library. The current integration also drops the duration from Brave, calculating it again in a manner that's wrong (the below is from what I had put into the pollinators slack)

> I have durations, and I see that this is being called, https://github.com/honeycombio/beeline-java/blob/main/beeline-spring-boot-sleuth-starter/src/main/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporter.java#L76
> however, when the root span is closed, I believe that may be replaced by this logic, https://github.com/honeycombio/beeline-java/blob/main/beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanPostProcessor.java#L53 which calls https://github.com/honeycombio/beeline-java/blob/main/beeline-core/src/main/java/io/honeycomb/beeline/tracing/Span.java#L315

the gist is sufficient for my needs, but likely has room for improvement. one notable thing is somehow figuring out how to get the rate associated with the brave sampling decision back into HC. we're currently running at a sample rate of 1 so it's a non-issue, but is something that should likely be fixed in the main library.

**Comment by MikeGoldsmith** [comment]
Thanks for the help.
Would you like to contribute the changes yourself, or are you happy for me to crate the PR (I'll attribute the changes to you)?

**Comment by osi** [comment]
You can take lead 😀 

I've gotten it "good enough" for the moment for my immediate needs, and need to spend time on some other tasks before i can pour more time into this one.

**Comment by MikeGoldsmith** [comment]
Sure, no problem. Thanks for the starter code 👍

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
