### ISSUE TITLE
Upgrade beeline-spring-boot-starter to 1.2.0 breaks  

### ISSUE THREAD

**Issue by babadofar** [honeycombio/beeline-java#81]
Upgrading `beeline-spring-boot-starter` to version 1.2.0 breaks my applications with this error message.
I guess this is related to  net.ttddyy and JDBC instrumentation
Using Spring boot version 2.3.3. 

````
Factory method 'h2Console' threw exception; nested exception is java.lang.ClassCastException: class net.ttddyy.dsproxy.support.ProxyDataSource cannot be cast to class com.zaxxer.hikari.HikariDataSource (net.ttddyy.dsproxy.support.ProxyDataSource and com.zaxxer.hikari.HikariDataSource are in unnamed module of loader 'app'

**Comment by MikeGoldsmith** [comment]
Hi @babadofar - thanks for raising the issue. I'll take a look and get back to you soon.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
