### ISSUE TITLE
How should I use honeycomb in a Java AWS lambda?

### ISSUE THREAD

**Issue by chaoyangnz** [honeycombio/beeline-java#82]
It is not a Spring web application, just a vanilla Java application running in AWS Lambda.

when I am using honeycomb in a Java lambda, and found I have to close the client explicitly in each invocation. Otherwise, the root trace is missing in Honeycomb web UI.

If I reuse the client across multiple lambda runs, the JVM shutdown hook is never triggered, which further cause the event is missing.

What is the correct usage of Honeycomb in a Java lambda?

**Comment by MikeGoldsmith** [comment]
Hi @chaoyangnz  - thanks for raising the query.

Currently, the best way to use the beeline-line in an AWS lambda function is to instantiate and close the beeline to ensure all trace spans are sent to Honeycomb. This is because the flush action is internal and only called during close.

If it were possible to manually flush pending spans, the beeline instance could used across multiple lambda invocations. This could be done by extending the [DefaultBatcher](https://github.com/honeycombio/libhoney-java/blob/389f75e34703f50cf288a30c686277426cf41ae5/libhoney/src/main/java/io/honeycomb/libhoney/transport/batch/impl/DefaultBatcher.java) in libhoney-java. However, I'm uncertain if there is enough resource locking / management to allow that right now.

**Comment by chaoyangnz** [comment]
Thanks @MikeGoldsmith 

Even I call the internal flush to submit all events in the queue, the last event is still missing. I looked into the source code, I think that is caused by the asyncHttpClient, which return a Future but never checked to make sure the response is received.

Currently my workaround is to wait several seconds after a lambda invocation so that there is enough time for honeycomb to send events on the fly. Not a elegant solution, but works.

**Comment by MikeGoldsmith** [comment]
Thanks @chaoyangnz - I'll take a look at your suggestion of the future not completing correctly.

FYI we're planning on making the libhoney/beelines consistent by providing a public `flush()`. No timeline yet, but we're hopeful it won't be too long.

**Comment by chaoyangnz** [comment]
Thanks. Hopefully, when I call the public ‘flush’, it can not only submit events in the batching queue but also make sure requests to honeycomb get responses. So after that, I am sure it is really a flush.

And feel free to close this issue

**Comment by MikeGoldsmith** [comment]
I'll leave this open and tag it when we move forward with the flush PR 👍

**Comment by JamieDanielson** [comment]
We are not planning to add new features to the beeline, though any changes will be added into release notes. We are recommending the use of OpenTelemetry, and specifically our [Honeycomb OpenTelemetry Distribution for Java](https://github.com/honeycombio/honeycomb-opentelemetry-java).

We're going to close this issue but feel free to submit a new issue or request a re-open if this is still relevant.
