### ISSUE TITLE
Support for Spring WebFlux

### ISSUE THREAD

**Issue by mveitas** [honeycombio/beeline-java#88]
Recently ran into an issue where some of our engineering teams are running Spring Webflux. The existing Beeline only supports servlet-based web applications.

**Comment by MikeGoldsmith** [comment]
Hi @mveitas - thanks for raising the issue. We'll look into if / when that is something we can support. I've created a ticket on our internal ticketing system to triage / investigate.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
