### ISSUE TITLE
Are alternative sampling methods impossible to implement with beelines?

### ISSUE THREAD

**Issue by plmaheu** [honeycombio/beeline-java#89]
I've been trying for a while to customize how sampling is done in a beeline but so far have been unsucessful. What I'd like to do basically is to modify sample rates depending of the root span, so information that is available at the start of the trace. However I can't achieve this because the sample rate is frozen deep in SpanBuilderFactory, there's no way to make it dynamic. 

On one side I see documentation like https://docs.honeycomb.io/working-with-your-data/best-practices/sampling/ describing sampling methods and on the other the design of the beelines seem to make it impossible. Is there something I'm missing or the beelines are not intended to allow different sampling strategies?

**Comment by mveitas** [comment]
This is something new that might help: https://github.com/honeycombio/refinery

**Comment by plmaheu** [comment]
@mveitas Thanks for the link. It might be of use eventually but for the moment I'm more looking for a code solution. Adding more infra is something I'd rather avoid in the system I'm working on.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
